[package]
name = "memlib"
version = "0.1.0"
authors = ["Ryan McCrystal <rrmccrystal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
32-bit = []

[dependencies]
system-host = { path = "./system-host" }

log = "0.4.8"
regex = "1.3.9"
impl_ops = "0.1.1"
pretty-hex = "0.1.1"
colored = "2.0.0"
nalgebra = "0.21.1"
tarpc = "0.21.0"
serde = "1.0.114"
tokio = { version = "0.2.22", features = ["rt-threaded"] }
tokio-serde = { version = "0.6.1", features = ["json"] }
futures = "0.3.5"
lazy_static = "1.4.0"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["memoryapi", "processthreadsapi", "tlhelp32", "ntdef", "handleapi"] }
[target.'cfg(target_os = "linux")'.dependencies]
vmread = "0.1.5"
