[package]
name = "memlib"
version = "0.1.0"
authors = ["Ryan McCrystal <rrmccrystal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
32-bit = []

[dependencies]
log = "0.4.8"
regex = "1.3.9"
pretty-hex = "0.1.1"
nalgebra = "0.21.1"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["memoryapi", "processthreadsapi", "tlhelp32", "ntdef", "handleapi"] }
[target.'cfg(target_os = "linux")'.dependencies]
vmread = "0.1.5"
